### ISSUE TITLE
AlloyEditor

### ISSUE THREAD

**Issue by AraneaDev** [JefMari/awesome-wysiwyg#15]
AlloyEditor is NOT standalone .. it requires React, I just wasted a lot of time getting it to work ;)

**Comment by AraneaDev** [comment]
It's especially an issue in a webpack environment. It keeps crashing on react and react-dom even when you include the no-react version (which just means it doesn't have bundled react, it still needs it ><)

**Comment by JefMari** [comment]
>_<
With this issue, need PR for transferring it to React Issue~
