### ISSUE TITLE
Add Embeddable_TinyMCE-3 to the list

### ISSUE THREAD

**Issue by gryLeader** [JefMari/awesome-wysiwyg#46]
Embeddable_TinyMCE-3 is a mod of the TinyMCE 3.x WYSIWYG HTML editor. 
It can be integrated into offline desktop applications using Webbrowser component, or be used online as Rich Text Editor. 
Supports IE6-7 as well as modern browsers.
Link: https://github.com/gryLeader/Embeddable_TinyMCE3

**Comment by JefMari** [comment]
Hi @gryLeader ,

Please make a PR for this one. thank you.
